antony-jeong/MmArk

.gitignore
".gitignore" is added to the root. ".vscode/" is in the ".gitignore".
=> Apply new gitignore in the root (Add .vscode in the gitignore)

mmark/src/components/Sheet.js, mmark/src/components/sheet/Note.js, mmark/src/components/sheet/Triplet.js
=> rest placeholder

mmark/src/components/Sheet.js, mmark/src/components/sheet/Note.js, mmark/src/components/sheet/Triplet.js, mmark/src/pages/Main.js
=> finish placeholder

mmark/src/components/audio-parts/SheetPlayer.js, mmark/src/components/audio-parts/SoundPlayer.js
Add loudness feature for notes with accent decoration
=> Add loudness feature for notes with accent decoration

mmark/src/components/Piano.js
Add addPlayHistory prop to Piano
=> Add addPlayHistory prop to Piano

mmark/src/components/Sheet.js
Add play/stop button for sheet
=> Add play/stop button for sheet

mmark/src/components/audio-parts/SheetPlayer.js
Fix errors on playing Fb and Cb
=> Fix errors on playing Fb and Cb

mmark/src/components/audio-parts/SheetPlayer.js
Fix error on calculating octave
=> Fix error on calculating octave

mmark/src/components/audio-parts/SheetPlayer.js
Fix error in calculating octave
=> Fix error in calculating octave

mmark/src/components/audio-parts/SheetPlayer.js
Fix error in removing highlight when play terminates
=> Fix error in removing highlight when play terminates

mmark/src/components/audio-parts/SheetPlayer.js
=> Fix highlight pausing error

mmark/src/components/utils/calcSheetObjectMargin.js
Implement except triplet and error handling
=> Implement except triplet and error handling

mmark/src/components/utils/calcSheetObjectMargin.js
=> Fix integer division error

mmark/src/components/audio-parts/SheetPlayer.js
=> Add playing state announcer

mmark/src/components/piano-parts/PianoKey.js
=> Remove piano key label

mmark/src/components/piano-parts/PianoKey.css
=> Change C4 indicator

mmark/src/components/audio-parts/SheetPlayer.js
Fix isPlaying state change error
=> Fix isPlaying state change error

mmark/src/LearnNoteData.js
=> Change BPMs

mmark/src/components/audio-parts/SheetPlayer.js
Fix error in cancelling accidentals after each bar line
=> Fix error in cancelling accidentals after each bar line

mmark/src/components/Sheet.js
Fix bug - sheet player doesn't stop when page changes
=> Fix bug - sheet player doesn't stop when page changes

mmark/src/LearnRhythmData.js
=> Correct rhythm game data bpm)

mmark/src/LearnNoteData.js
=> Modify instruction

mmark/src/LearnRhythmData.js
=> Correct pageId

mmark/src/components/utils/calcSheetObjectMargin.js
=> Change doubleaBar width

mmark/src/components/SheetEditControl.js, mmark/src/stylesheets/Learn.css
=> Change some of button shapes

mmark/src/components/SheetEditControl.js, mmark/src/stylesheets/Learn.css
Apply styles and text for DP5 presentation
=> Apply styles and text for DP5 presentation

mmark/src/components/SheetEditControl.js
Apply styles and text for DP5 presentation +1
=> Apply styles and text for DP5 presentation +1

articles/views.py, config/urls.py, mmark/src/components/CommunityBlock.js, mmark/src/pages/Community.js, mmark/src/pages/Login.js, mmark/src/stylesheets/Community.css
=> Apply for backend
